### PR TITLE
Add docs.rs changes

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Comment by nellshamrell** [comment]
@llogiq, since you handle this section, what are your thoughts on this change?

**Comment by jyn514** [comment]
Let me know if I should give more context on the changes :) most of the PRs have screenshots if they're frontend related.

**Comment by jyn514** [comment]
Looks like this missed the cutoff. For next time, what should I do to make sure this gets reviewed in time?

**Comment by nellshamrell** [comment]
@llogiq I know you have some scripts that fill in these portions of the newsletter. Is it possible to include manually added updates like this one as well?

**Pull request closed without merging**
