### PR TITLE
writing database in rust

### PR DESCRIPTION
**Pull request by alex-dukhno**
first time sharing my blog post through `This week in Rust`

Thank you!

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hello there! This feels like it would be a better fit in the "Call for Participation" section - do you mind if I move it there?

**Comment by alex-dukhno** [comment]
Hi, not a problem 😄 

thanks

**Comment by alex-dukhno** [comment]
I resolved conflict with placing the article under "Call for Participation" section

**Comment by nellshamrell** [comment]
Thank you!

**Pull request merged**
