### PR TITLE
Add blog post

### PR DESCRIPTION
**Pull request by thomaseizinger**
Disclaimer: I am the author of the post. It showcases some of rustc's features and how they can be used in conjunction with certain design patterns to avoid writing integration tests.

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hi there! I have already finalized and published this issue https://this-week-in-rust.org/blog/2020/07/28/this-week-in-rust-349/

However, I would love to consider this for next week's issue. I will post here when I have that draft available in this repo (should be later today).

**Comment by thomaseizinger** [comment]
Hey @nellshamrell,

thanks for coming back to this! No worries, I will just rebase onto the new draft then if that is ok :)

**Comment by nellshamrell** [comment]
Go right ahead! New draft is [here](https://github.com/emberian/this-week-in-rust/blob/master/draft/2020-08-04-this-week-in-rust.md).

**Comment by thomaseizinger** [comment]
Done :)

**Pull request merged**
