### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by inshalayaz**
Can you add my contribution on this week in rust like my other article,

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hello @inshalayaz! Could you please add the link to the current [draft of this week's issue](https://github.com/emberian/this-week-in-rust/blob/master/draft/2020-07-07-this-week-in-rust.md]?

You can follow the example in [this pull request](https://github.com/emberian/this-week-in-rust/pull/1338)

**Comment by inshalayaz** [comment]
I've already made a pull request I'll make an other one

**Comment by inshalayaz** [comment]
I've created the pull request can you check please

**Comment by nellshamrell** [comment]
Hello there! I see your pull request, but it's not putting the change in the correct file for me to accept it. I'd love to include this article, but need you to add the link to the file at draft/2020-07-07-this-week-in-rust.md. If you need an example of how to add a link specifically to this file, please take a look at [this pull request](https://github.com/emberian/this-week-in-rust/pull/1338).

**Comment by inshalayaz** [comment]
Ok I did that can you check now please I added it in the draft 2020-07-07

**Comment by nellshamrell** [comment]
Closing as this was merged in #1343

**Pull request closed without merging**
