### PR TITLE
mention payment available

### PR DESCRIPTION
**Pull request by programmerjake**

### CODE REVIEW

**Comment by cdmistman** [comment]
@programmerjake thanks for trying to inform our readers that there is payment available, but I'd like to verify this before we accept your PR. Do you have a bounty for this task, and if so is the payment in escrow?

**Comment by programmerjake** [comment]
the payment is in the form of a donation from https://nlnet.nl/, see https://nlnet.nl/project/Libre-RISCV/

**Comment by programmerjake** [comment]
> Do you have a bounty for this task,

yes, we effectively have a €400 bounty, though stated differently.
> and if so is the payment in escrow?

not strictly, though the organization paying is not libre-soc itself, it's nlnet who has agreed to pay on our behalf.

**Comment by programmerjake** [comment]
the payment amount is somewhat negotiable.

**Pull request merged**
