### PR TITLE
Make newsletter theme more responsive

### PR DESCRIPTION
**Pull request by dvogt23**
Issue: #1017

### CODE REVIEW

**Comment by dvogt23** [comment]
Here are some screenshots for comparr:
EC383AE3-FEF7-4AB3-A7F7-102C5BDEA655
91838927-1190-44AB-81D4-C36E12D38735

**Comment by nasa42** [comment]
While this seems to work in web and Android email clients, in iPhone email clients (all iPhone versions), the fonts are way too big to be readable (tested on multiple platforms using Mailchimp and Litmus). I think for emails, we'll have to stick to `px`.

**Comment by nasa42** [comment]
This screenshot is from iPhone X (via Mailchimp/litmus preview).

iphonex-vertical-allowed-1366

**Comment by nellshamrell** [comment]
This has been open for some time, I'm going to go ahead and close it, but if you are able to address the issues around rendering on iPhones feel free to re-open!

**Pull request closed without merging**
