### PR TITLE
Add RustFest announcement

### PR DESCRIPTION
**Pull request by dns2utf8**
We will merge the post in the next hours
https://github.com/RustFestEU/blog.rustfest.eu/pull/99

Cheers,
Stefan

### CODE REVIEW

**Comment by nellshamrell** [comment]
Hurray!

**Comment by dns2utf8** [comment]
Thank you! :smiley:

**Comment by dns2utf8** [comment]
It is public now

**Comment by RafaelaWetzel** [comment]
Awesomeness!

**Pull request merged**
