### PR TITLE
A txt file to have a backup links of previous TWiR

### PR DESCRIPTION
**Pull request by hmble**
I don't know if this is right idea to include a backup text file of links in `News and Blog` section of previous TWiR articles.
This file contains links from TWir 96 ( 2015-09-14  ) to TWiR 339  ( 2020-05-19 ).

If you don't like this idea feel free to close this PR.

Here is the [raw](https://raw.githubusercontent.com/hmble/news_blog/master/links.txt) file I mention in issue #1222 for reference as this diff is quite large.

### CODE REVIEW

**Comment by nellshamrell** [comment]
Seems like a good idea! Are you able to help keep it updated from week to week?

**Comment by hmble** [comment]
Yes sure. I will update links once an article gets published

**Comment by nellshamrell** [comment]
Sounds great! Merging!

**Comment by hmble** [comment]
Thanks

**Pull request merged**
